version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"
    volumes:
      - telegrambot_db:/var/lib/mysql
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5

  telegram_bot:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: .
    restart: always
    env_file: ./.env
    stdin_open: true
    tty: true
    networks:
      - my_network

volumes:
  telegrambot_db:

networks:
  my_network:
