version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - my_network
  telegram_bot:
    depends_on:
      - mysqldb
    build: .
    restart: always
    env_file: ./.env
    stdin_open: true
    tty: true
    networks:
      - my_network



volumes:
  db:

networks:
  my_network:

